name: Deploy Services to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy Services
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4: Build and push Docker images to ECR
      - name: Build and Push Docker Images
        run: |
          SERVICES=("appointment" "doctors" "notification" "patients")
          ECR_REPO="${{ secrets.ECR_REPOSITORY_URL }}"

          for SERVICE in "${SERVICES[@]}"
          do
            echo "Processing $SERVICE..."

            IMAGE_TAG="$SERVICE-service"

            # Navigate to the service directory
            cd $SERVICE

            # Build the Docker image
            docker build -t $ECR_REPO:$IMAGE_TAG .

            # Push the Docker image to ECR
            docker push $ECR_REPO:$IMAGE_TAG

            # Return to the root directory
            cd ..
          done

      # Step 5: Sleep for 120 seconds
      - name: Wait for 120 seconds before starting
        run: sleep 120

      # Step 6: Configure kubectl for EKS
      - name: Configure kubectl for EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name <cluster-name>
          

      # Step 7: Apply Kubernetes manifests
      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f config-map.yaml
          kubectl apply -f api-gateway-deployment.yaml
          kubectl apply -f appointment-deployment.yaml
          kubectl apply -f authentication-deployment.yaml
          kubectl apply -f doctor-deployment.yaml
          kubectl apply -f notification-deployment.yaml
          kubectl apply -f patient-record-deployment.yaml
          kubectl apply -f report-deployment.yaml
