name: Docker Images Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Step 4: Build and push Docker images
      - name: Build and push Docker images
        run: |
          SERVICES=("appointment-service" "doctors-service" "notification-service" "patient-service")
          for SERVICE in "${SERVICES[@]}"
          do
            # Navigate to the service directory
            cd $SERVICE

            # Build the Docker image
            docker build -t ${{ secrets.ECR_REPOSITORY_URL }}/$SERVICE:latest .

            # Push the Docker image to ECR
            docker push ${{ secrets.ECR_REPOSITORY_URL }}/$SERVICE:latest

            # Return to the root directory
            cd ..
          done
